# Generated by Django 3.1.7 on 2021-03-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
